### PR TITLE
add user role set

### PR DESCRIPTION
**Pull request by Shaoshian**
Signed-off-by: root <shianx.a.shao@intel.com>

### CODE REVIEW

**Comment by xuechendi** [comment]
@Shaoshian , how about the UI? can you sync with yu,qi

**Comment by Shaoshian** [comment]
@xuechendi   ui部分，yuqi说这两天完成，上周问他的时候，他好像手上有测试要做。

**Comment by xuechendi** [comment]
@Shaoshian , Ok, please assist him to complete UI work, great thanks! Let's start review after that.

**Comment by Shaoshian** [comment]
@xuechendi   ok.

**Comment by Shaoshian** [comment]
@xuechendi    修改了  你看一下

**Pull request merged**
