### PR TITLE
add config param

### PR DESCRIPTION
**Pull request by yonghengdexin735**
if having multi-client, `group-reporting` is necessary

Signed-off-by: zhang.zezhu zhang.zezhu@zte.com.cn

### CODE REVIEW

**Comment by xuechendi** [comment]
@yonghengdexin735 , can you explain it more specific?

**Comment by yonghengdexin735** [comment]
@xuechendi  in fio `--group-reporting` can collect data for sum two or more clients of returning data for fio test.  If didn't add this param the return data is only one of the clients.

**Comment by xuechendi** [comment]
@yonghengdexin735 , but under cetune scope, each fio only runs one fio client job, and if you wanna run multi-fio jobs, actually one physical node will start lots of fio jobs. 
And I am worried that even we add --group-reporting, cetune still only calculate the first fio job printout??
Or did you do this multi client test in your own env, and does it works with the modified cetune? Can you share your desired result and address your problem more clear??

**Comment by yonghengdexin735** [comment]
@xuechendi , this example is my fault, but adding `--group_reporting` is necessary for fio test. When one client for fio test used `numjobs`, like `numjobs=32`: 
Firstly, if you don't add `group_reporting` to fio.conf, CeTune will colloct only one numjob data for IOPS showed in CeTune web.
socondly, if you add `group_reporting` to fio.conf, CeTune will collect all numjobs data for IOPS displayed in web.

**Comment by yonghengdexin735** [comment]
@xuechendi  for my test, fio.conf is 
**[global]
    direct=1
    time_based
[generic-randread-4k-qd128-800g-40-30-generic]
    rw=randread
    bs=4k
    iodepth=128
    ramp_time=40
    runtime=30
    numjobs=32
    ioengine=libaio
    filename=${DEVICE}
    iodepth_batch_submit=1
    iodepth_batch_complete=1
**
when I didn't add `group_reporting`, the result for IOPS displayed in CeTune web was `86` , and then adding `group_reporting` to fio.conf , the result for IOPS showed in web was `2793` which is closed proximity to `86*32`. So adding `group_reporting` in code is essential.

**Comment by xuechendi** [comment]
@yonghengdexin735 , I got what you plan to do, actually, we found using numjob brought in some fio overhead than using multi fio processes, so when you set workers number more than physical clients, cetune will run more than one fio processes on one node rather than modify the numjobs, that is also why we won't run into the situation you assumed above.
Anyway, if you prefer using numjobs , just use numjobs, in cetune , I didn't see strong reason to switch to numjobs yet .

**Comment by yonghengdexin735** [comment]
@xuechendi , hi , using  CeTune web to config fio, workers number is means numjobs for fio.conf, so if workers number = 32, means numjobs=32

**Comment by yonghengdexin735** [comment]
@xuechendi the above of fio.conf automatically generated in CeTune. I just discussed whether adding group_reporting to code. Actually this is only one client for my argument

**Comment by xuechendi** [comment]
@yonghengdexin735 , It's weird, I never set numjobs in cetune codes, as I told, when you config workers in cetune webui, you should see the same number or double number of fio processes rather than threads.

**Comment by yonghengdexin735** [comment]
@xuechendi hi, I have question for nic, in CeTune using sar to collect network data, but I don't know how CeTune compute data  for network, and here collect for public network or cluster network

**Comment by xuechendi** [comment]
@yonghengdexin735 , not quite sure about what you asking. For the network data analysis, you can refer to the analyze.py. Basically, cetune collect sar data by sec.

**Comment by yonghengdexin735** [comment]
@xuechendi I have two NIC (10GbE 82599), one for ceph public_network, another for ceph cluster_network. which one data for sar in collocton?

**Comment by xuechendi** [comment]
@yonghengdexin735 , all of them will be collected.
And current cetune will sum up all nic recv bytes ( trans bytes ) by sec to final report.

**Comment by yonghengdexin735** [comment]
@xuechendi why not collect,respectively

**Comment by xuechendi** [comment]
@yonghengdexin735 , hum? I think you miss my point? 
"all of them be collected" as I mentioned above

**Pull request closed without merging**
